export const posModifiers: any[] = [
	"4k",
	"8k",
	"Trending on Deviant Art",
	"Trending on CGSociety",
	"Trending on Artstation",
	"Anime",
	"Manga",
	"Comic book panel",
	"Poster",
	"Wallpaper",
	"Octane",
	"Render",
	"Realisitic",
	"Wide angle",
	"Vertical Wallpaper",
	"Inked",
	"Concept art",
	"Ultrafine",
	"Hyperdetail",
	"Global illumination",
	"Precise",
	"Heavy Metal comics",
	"Scifi",
	"Bold lines",
	"Pencil",
	"Intricate detail",
	"Detailed line art",
	"Cinematic",
	"Cinematic atmosphere",
	"Top view",
	"Cyberpunk",
	"Retrofuture",
	"Retropunk",
];
