const styleList: string[] = [
	"Comic art",
	"Illustration",
	"Drawing",
	"Painting",
	"Matte painting",
	"Master painting",
	"Watercolor",
	"Oil Painting",
	"Renaissance era painting",
	"Mixed Media",
	"Chiaroscuro",
	"Ukiyo-e",
	"Render",
	"Graffiti",
	"2D",
	"3D",
	"Japanese woodblock print",
	"Screenprint",
	"Editiorial Illustration",
	"Cel-shading",
	"Inking",
	"Lineart",
	"Photography",
	"Stained Glass",
	"Lithograph",
	"Etching",
	"Othographic",
];

export default styleList;
